services:
  - type: web
    name: nome-do-seu-serviço  # Substitua pelo nome que você deseja
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -b 0.0.0.0:${PORT} teste_final:app"  # Certifique-se de qu